spec-sw: kernel: nic-core: last_rx is no more available since kernel > 4.11
struct net_device has no more last_rx. According to [1] this line must be
simply supressed for kernel > 4.11 to avoid build failure like :

spec-sw/kernel/wr_nic/nic-core.c: In function '__wrn_rx_descriptor':
spec-sw/kernel/wr_nic/nic-core.c:428:5: error: 'struct net_device' has no member named 'last_rx'
  dev->last_rx = jiffies;
     ^~
make[5]: *** [/usr/src/linux-headers-4.18.0-2-common/scripts/Makefile.build:323: spec-sw/kernel/wr_nic/nic-core.o] Error 1
make[4]: *** [/usr/src/linux-headers-4.18.0-2-common/Makefile:1531: _module_spec-sw/kernel] Error 2
make[3]: *** [Makefile:146: sub-make] Error 2
make[2]: *** [Makefile:8: all] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.18.0-2-amd64'
make[1]: *** [Makefile:20: all] Error 2
make[1]: Leaving directory 'spec-sw/kernel'
make: *** [Makefile:28: kernel] Error 2

[1] https://patchwork.ozlabs.org/patch/716831/

Signed-off-by: Gwenhael Goavec-Merou <gwenhael.goavec-merou@trabucayre.com>